name: Container build helper
on:
  workflow_dispatch:
  # schedule:
  #   - cron:  '0 */12 * * *'
  push:
      paths:
        - 'Dockerfile'
        - '.github/workflows/container.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Buildx setup
        id: buildx
        uses: docker/setup-buildx-action@master
        with:
          install: true

      - name: Build image
        uses: docker/build-push-action@master
        with:
          context: .
          file: Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          build-args: |
            SECRET_KEY=${{ secrets.CSRF_SECRET }}
          push: true
          tags: x0rzavi/quickread:latest
          cache-from: type=registry,ref=x0rzavi/quickread:buildcache
          cache-to: type=registry,ref=x0rzavi/quickread:buildcache,mode=max